### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Yao985** [SOUMEE2000/Netlogo-Models-of-Developer-Interaction#4]
Hello blogger, can you share the final version of the model in your manuscript? Didn't find that version in the final model! Super needy! Thanks a lot!

**Comment by SOUMEE2000** [comment]
Hello. Sorry that data is confidential. I hope the approach helps though. Thanks

**Comment by Yao985** [comment]
Hi, can you share the final version of the netlogo model? I didn't find that version in the manuscript. It is possible to share the data without it, thank you very much!

**Comment by Yao985** [comment]
Hi, can you share the final version of the netlogo model? I didn't find that version in the manuscript. Don't need the data for that. Thanks a lot!
